//
// Created by Tristan Whitcher on 3/9/16.
//

#ifndef CYCLOMETERCONTROLLER_EVENT_H
#define CYCLOMETERCONTROLLER_EVENT_H


enum Event {
    FULL_RESET,
    RESET_TRIP,
    MODE_BUTTON,
    MODE_TICK,
    SET_BUTTON,
    START_STOP_BUTTON,
    PULSE
};


#endif //CYCLOMETERCONTROLLER_EVENT_H
