//
// Created by Tristan Whitcher on 3/9/16.
//

#ifndef CYCLOMETERCONTROLLER_EVENT_H
#define CYCLOMETERCONTROLLER_EVENT_H


enum Event {
    FULL_RESET,
    RESET_TRIP,
    MODE_BUTTON,
    MODE_2_BUTTON,
    RELEASE_MODE_BUTTON,
    SET_BUTTON,
    RELEASE_SET_BUTTON,
    START_STOP_BUTTON,
    RELEASE_START_STOP_BUTTON,
};


#endif //CYCLOMETERCONTROLLER_EVENT_H
